### ISSUE TITLE
Google ReCaptcha - Missing Captcha Token

### ISSUE THREAD

**Issue by daamsie** [Charitable/Charitable-Spam-Blocker#4]
After setting up Google's ReCaptcha, the following error occurs when trying to post a form

![Screen Shot 2020-12-14 at 12 09 24 pm](https://user-images.githubusercontent.com/740324/102030067-51056a00-3e05-11eb-94af-8216ca38aa6b.png)

It is searching for the array key `grecaptcha_token` here and fails. 

`if ( ! array_key_exists( 'grecaptcha_token', $_POST ) ) {
				charitable_get_notices()->add_error( __( 'Missing captcha token.', 'charitable-spamblocker' ) );
				return false;
			}`

The key is actually `charitable_grecaptcha_token`

I'll create a pull request with a fix for this

**Comment by ericnicolaas** [comment]
Closed by  11ea6e0
