### ISSUE TITLE
It is unclear whether ReCaptcha V2, or V3 is being used.  

### ISSUE THREAD

**Issue by daamsie** [Charitable/Charitable-Spam-Blocker#5]
It's not really mentioned anywhere whether V2 or V3 are being used here. Since a lot of people still like to use V2, it should be made explicit somewhere.

**Comment by ericnicolaas** [comment]
Good point @daamsie. There is zero documentation for this plugin at the moment, but at least the name of the captcha option could include the fact that it's Invisible V2.

**Comment by daamsie** [comment]
Wait, Invisible V2? I thought it was V3. At least, when I tested locally with V3 keys it seemed to work! Not initially, but after fixing issue #4 it did. Hmm, maybe the keys work for both versions.

**Comment by ericnicolaas** [comment]
Yeah, Invisible V2. But interesting if it works with both! Seems odd unless the basic API has remained unchanged.
